service: senior-project-template

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-offline

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    TimeCard:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TimeCardData
        AttributeDefinitions:
          - AttributeName: projectName
            AttributeType: S
        KeySchema:
          - AttributeName: projectName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  login:
    handler: src/handlers/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  timeCard:
    handler: src/handlers/timeCard.handler
    events:
      - http:
          path: timeCard
          method: post
          cors: true
  getEmployeeData:
    handler: src/handlers/getEmployeeData.handler
    events:
      - http:
          path: getEmployeeData
          method: get
          cors: true

  

